name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t andrewskigar/quotes .

      - name: Push Docker Image to GitHub Container Registry (GHCR)
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag andrewskigar/quotes ghcr.io/andrewskigar/quotes:latest
          docker push ghcr.io/andrewskigar/quotes:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y unzip
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS Credentials
        run: |
          echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY > ~/.aws/credentials
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1  # Change to your preferred region

      - name: Deploy to AWS
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
